[[contracts]]
fqn = "oracle::oracle::PriceOracle"

[[contracts]]
fqn = "validator_registry::validator_registry::ValidatorRegistry"

[[contracts]]
fqn = "cusd::cusd::CUSD"

[[contracts]]
fqn = "yscspr::yscspr::YSCSPR"

[[contracts]]
fqn = "liquid_staking::liquid_staking::LiquidStaking"

[[contracts]]
fqn = "stayer::stayer::StayerVault"
