last_updated = "2026-01-05T15:00:40Z"

[[contracts]]
name = "PriceOracle"
package_hash = "hash-8e22cef38e428591db172c1da84078628f84fc93f83a53a50b8eeceb2fa86ae2"

[[contracts]]
name = "ValidatorRegistry"
package_hash = "hash-9cda3fe13c8958781e488b2045b13badca4572734cf86628cce84fda6a636ff1"

[[contracts]]
name = "CUSD"
package_hash = "hash-88ebf0537324d5bc17d47eefd31f11ee9b324c9008f4b55928c6cb6d59a62405"

[[contracts]]
name = "YSCSPR"
package_hash = "hash-946c8fcce75b60d91538155e19639611c71e994ba38a87fa66ae7945152b64e7"

[[contracts]]
name = "LiquidStaking"
package_hash = "hash-55323fe852a7c8b5f3f950e1a01cd3d073723f9f7b65db904f860266fbf92cc0"

[[contracts]]
name = "StayerVault"
package_hash = "hash-70bd0067e222e30ef202db1a0e846864784577861d759a7d7adde0900e1befca"
