last_updated = "2025-12-28T09:19:05Z"

[[contracts]]
name = "PriceOracle"
package_hash = "hash-3afd2f0f52a2b8de66c44b6ba97e6f056b5d9862fbb8736e647555ca242e74f9"

[[contracts]]
name = "ValidatorRegistry"
package_hash = "hash-976b6dc755f25fc6d2052e9a00d95c0a84516185a9ebad52a9df38482c09dee3"

[[contracts]]
name = "CUSD"
package_hash = "hash-eb59671387ed97325728ac586477899db2f43c1cffd963b7937e696f2389a3a1"

[[contracts]]
name = "YSCSPR"
package_hash = "hash-c381d0f5faff2d59badd6606fd696691c3fcccc0700ce897336461171eec92e6"

[[contracts]]
name = "LiquidStaking"
package_hash = "hash-4470231de5e030712f19811893339988fcc51f1bd8a3a10c6732dd5481c0fef5"

[[contracts]]
name = "StayerVault"
package_hash = "hash-ccfa385e56c514710643f171154eab09512a4650de5ee52c90af09d3ef40dddb"
