last_updated = "2025-12-25T17:36:13Z"

[[contracts]]
name = "PriceOracle"
package_hash = "hash-b2729cbc692fd8d663d57098d984fd9bee740b28b18dcef05473e78bca0dd48e"

[[contracts]]
name = "ValidatorRegistry"
package_hash = "hash-b5a2a4124adf3b42b8e864b6581491b5e81bdde7fea8b6681ba59a59eb3d8db9"

[[contracts]]
name = "CUSD"
package_hash = "hash-2a9f1ebb877b16cf6cd5cc313ff405f69eee8259ab342e3c062bffb8181a91b3"

[[contracts]]
name = "YSCSPR"
package_hash = "hash-43059de00c77a9164a950fc46f1c312c6d08cef60d7a15cd9686b8120c7d360e"

[[contracts]]
name = "LiquidStaking"
package_hash = "hash-e5f9a0dbc64ea9ce5a2e8421e5d12684c0fbcaf86accdf1925d829b096fe77f0"

[[contracts]]
name = "StayerVault"
package_hash = "hash-7ff4730f56fb73de61b6f632ff36c15f6adedf115259e9caa07eac0f3bd4d843"
