last_updated = "2026-01-04T16:39:03Z"

[[contracts]]
name = "PriceOracle"
package_hash = "hash-dc31c91eb6686d9133ac9074f5e345c177ecdc0f2466e037e4c511113a963cc4"

[[contracts]]
name = "ValidatorRegistry"
package_hash = "hash-f625876594941b55714c4c3126dc57ff2a0dd7bdd4fbb41b5b97c77e8392d369"

[[contracts]]
name = "CUSD"
package_hash = "hash-e90070936a15a66b00c95cc55dbb5b979ac41fa16425db23c2a3a42d1e26082e"

[[contracts]]
name = "YSCSPR"
package_hash = "hash-6338e429a9f8bc8676d39251d81b990394dcc0014c738d68a7137e2a46808657"

[[contracts]]
name = "LiquidStaking"
package_hash = "hash-071c659d24f91a87a3a92ab40394fa46c9c969ec93dbd780848f814198272ab3"

[[contracts]]
name = "StayerVault"
package_hash = "hash-e51fab33128dfd91f39711cb71021419c32d9782083dd5c888757824c064b44c"
